server:
  port: 8764 #服务端口

eureka:
  client:
    serviceUrl: #指定服务注册中心地址，类型为 HashMap，并设置有一组默认值，默认的Key为 defaultZone；默认的Value为 http://localhost:8761/eureka ，如果服务注册中心为高可用集群时，多个注册中心地址以逗号分隔
      defaultZone: http://localhost:8761/eureka/  #Eureka客户端和服务端进行交互的地址，服务注册中心的地址

spring:
  application:
    name: service-ribbon  #服务名
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
      discovery:
        enabled: true
        service-id: config-server
eureka-client:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 设置负载策略
## 刷新时，关闭安全验证
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info  #配置actuator暴露的接入点，默认只有health和info，所以要添加refresh
  security:
    enabled: false

endpoints:
  actuator:
    enabled: true